/**** Auto-Generated By REFU,Don't Modify it Manually ****/
using UnityEngine;
using System.Collections.Generic;

//Generated by Sheet : Person
public class Person : ScriptableObject {
    //Auto-Generated Field : Name
    public System.String[] Name;

    //Auto-Generated Field : Age
    public System.Int32[] Age;

    //Auto-Generated Field : Money
    public System.Double[] Money;

}
