/**** Auto-Generated By REFU,Don't Modify it Manually ****/
using UnityEngine;
using System.Collections.Generic;

//Use Sourcefile Name as Namespace
namespace TestExcel_C {
//Generated by Sheet : GPA
public class GPA : ScriptableObject {
    //Auto-Generated Field : Grade
    public System.UInt32[] Grade;

    //Auto-Generated Field : Score
    public System.UInt64[] Score;

    //Auto-Generated Field : Addition
    public System.String[] Addition;

}
}
